gAbilityDescription_None: @ 81F99CC
	.string "Ningúna habilidad especial.$"

gAbilityDescription_Stench: @ 81F99E0
	.string "Aleja a POKéMON salvajes.$"

gAbilityDescription_Drizzle: @ 81F99FA
	.string "Hace que llueva en combate.$"

gAbilityDescription_SpeedBoost: @ 81F9A12
	.string "Va subiendo la VELOCIDAD.$"

gAbilityDescription_BattleArmor: @ 81F9A2A
	.string "Bloquea golpes críticos.$"

gAbilityDescription_Sturdy: @ 81F9A40
	.string "Anula golpes fulminantes.$"

gAbilityDescription_Damp: @ 81F9A5A
	.string "Evita la autodestrucción.$"

gAbilityDescription_Limber: @ 81F9A75
	.string "Evita la parálisis.$"

gAbilityDescription_SandVeil: @ 81F9A89
	.string "Más EVASIÓN en torm. arena.$"

gAbilityDescription_Static: @ 81F9AA5
	.string "Paraliza al mín. contacto.$"

gAbilityDescription_VoltAbsorb: @ 81F9ABB
	.string "Cambia electricidad en PS.$"

gAbilityDescription_WaterAbsorb: @ 81F9AD6
	.string "Convierte el agua en PS.$"

gAbilityDescription_Oblivious: @ 81F9AED
	.string "Evita la atracción.$"

gAbilityDescription_CloudNine: @ 81F9B02
	.string "Anula el efecto del clima.$"

gAbilityDescription_CompoundEyes: @ 81F9B1B
	.string "Aumenta la PRECISIÓN.$"

gAbilityDescription_Insomnia: @ 81F9B2C
	.string "Evita el quedarse dormido.$"

gAbilityDescription_ColorChange: @ 81F9B3C
	.string "Toma el tipo del mov rival.$"

gAbilityDescription_Immunity: @ 81F9B58
	.string "Evita el envenenamiento.$"

gAbilityDescription_FlashFire: @ 81F9B6C
	.string "Se carga si recibe fuego.$"

gAbilityDescription_ShieldDust: @ 81F9B86
	.string "Evita efectos secundarios.$"

gAbilityDescription_OwnTempo: @ 81F9B9E
	.string "Evita la confusión.$"

gAbilityDescription_SuctionCups: @ 81F9BB2
	.string "Fija el cuerpo con firmeza.$"

gAbilityDescription_Intimidate: @ 81F9BCB
	.string "Baja el ATAQUE del rival.$"

gAbilityDescription_ShadowTag: @ 81F9BE4
	.string "Evita que el enemigo huya.$"

gAbilityDescription_RoughSkin: @ 81F9BFF
	.string "Hiere al tacto.$"

gAbilityDescription_WonderGuard: @ 81F9C0F
	.string "Cuesta mucho hacerle daño.$"

gAbilityDescription_Levitate: @ 81F9C27
	.string "No sufre at. tipo TIERRA.$"

gAbilityDescription_EffectSpore: @ 81F9C42
	.string "Deja esporas al contacto.$"

gAbilityDescription_Synchronize: @ 81F9C5C
	.string "Transmite problem. estado.$"

gAbilityDescription_ClearBody: @ 81F9C77
	.string "Evita que baje la hab.$"

gAbilityDescription_NaturalCure: @ 81F9C93
	.string "Se cura al salir.$"

gAbilityDescription_LightningRod: @ 81F9CAD
	.string "Frena ataques eléctricos.$"

gAbilityDescription_SereneGrace: @ 81F9CC5
	.string "Añade efectos secundarios.$"

gAbilityDescription_SwiftSwim: @ 81F9CDD
	.string "Con lluvia, sube VELOCIDAD.$"

gAbilityDescription_Chlorophyll: @ 81F9CF3
	.string "Con sol, sube la VELOCIDAD.$"

gAbilityDescription_Illuminate: @ 81F9D0D
	.string "Facilita el encuentro.$"

gAbilityDescription_Trace: @ 81F9D27
	.string "Copia habilidad especial.$"

gAbilityDescription_HugePower: @ 81F9D3F
	.string "Aumenta el ATAQUE.$"

gAbilityDescription_PoisonPoint: @ 81F9D4E
	.string "Envenena al mín. contacto.$"

gAbilityDescription_InnerFocus: @ 81F9D66
	.string "Evita el retroceso.$"

gAbilityDescription_MagmaArmor: @ 81F9D7A
	.string "Evita el congelamiento.$"

gAbilityDescription_WaterVeil: @ 81F9D8D
	.string "Evita las quemaduras.$"

gAbilityDescription_MagnetPull: @ 81F9D9D
	.string "Atrapa POKéMON de ACERO.$"

gAbilityDescription_Soundproof: @ 81F9DB7
	.string "Evita ataques de sonido.$"

gAbilityDescription_RainDish: @ 81F9DD1
	.string "Sube PS cuando llueve.$"

gAbilityDescription_SandStream: @ 81F9DED
	.string "Crea una tormenta de arena.$"

gAbilityDescription_Pressure: @ 81F9E02
	.string "Baja los PP del enemigo.$"

gAbilityDescription_ThickFat: @ 81F9E19
	.string "Protege del frío y calor.$"

gAbilityDescription_EarlyBird: @ 81F9E33
	.string "Despierta rápido al PKMN.$"

gAbilityDescription_FlameBody: @ 81F9E4F
	.string "Quema al mínimo contacto.$"

gAbilityDescription_RunAway: @ 81F9E69
	.string "Facilita la huida.$"

gAbilityDescription_KeenEye: @ 81F9E80
	.string "Evita que baje PRECISIÓN.$"

gAbilityDescription_HyperCutter: @ 81F9E9B
	.string "Evita que baje el ATAQUE.$"

gAbilityDescription_Pickup: @ 81F9EB6
	.string "Puede tomar objetos.$"

gAbilityDescription_Truant: @ 81F9EC9
	.string "Interviene cada 2 rondas.$"

gAbilityDescription_Hustle: @ 81F9EE5
	.string "Cambia PRECIS. por energía.$"

gAbilityDescription_CuteCharm: @ 81F9F00
	.string "Emboba al mínimo contacto.$"

gAbilityDescription_Plus: @ 81F9F17
	.string "Mejora con habilidad MENOS.$"

gAbilityDescription_Minus: @ 81F9F2D
	.string "Mejora con habilidad MÁS.$"

gAbilityDescription_Forecast: @ 81F9F42
	.string "Cambia con el clima.$"

gAbilityDescription_StickyHold: @ 81F9F5C
	.string "Evita el robo de objetos.$"

gAbilityDescription_ShedSkin: @ 81F9F71
	.string "Se cura mudando la piel.$"

gAbilityDescription_Guts: @ 81F9F8D
	.string "Sube el ATAQUE si sufre.$"

gAbilityDescription_MarvelScale: @ 81F9FA6
	.string "Sube la DEFENSA si sufre.$"

gAbilityDescription_LiquidOoze: @ 81F9FC0
	.string "Al verterlo, hiere.$"

gAbilityDescription_Overgrow: @ 81F9FD8
	.string "Sube ataques tipo PLANTA.$"

gAbilityDescription_Blaze: @ 81F9FF4
	.string "Sube ataques tipo FUEGO.$"

gAbilityDescription_Torrent: @ 81FA00F
	.string "Sube ataques tipo AGUA.$"

gAbilityDescription_Swarm: @ 81FA02B
	.string "Sube ataques tipo BICHO.$"

gAbilityDescription_RockHead: @ 81FA045
	.string "Evita volver a ser golpeado.$"

gAbilityDescription_Drought: @ 81FA05D
	.string "Toma luz solar en batalla.$"

gAbilityDescription_ArenaTrap: @ 81FA079
	.string "Evita la huida.$"

gAbilityDescription_VitalSpirit: @ 81FA08B
	.string "Evita quedarse dormido.$"

gAbilityDescription_WhiteSmoke: @ 81FA09B
	.string "Evita que baje la habilidad.$"

gAbilityDescription_PurePower: @ 81FA0B7
	.string "Aumenta el ATAQUE.$"

gAbilityDescription_ShellArmor: @ 81FA0C6
	.string "Bloquea golpes críticos.$"

gAbilityDescription_Cacophony: @ 81FA0DC
	.string "Evita ataques de sonido.$"

gAbilityDescription_AirLock: @ 81FA0F6
	.string "Niega los efectos de clima.$"
	
gAbilityDescription_BadDreams: @ 81FA0F6
	.string "Lastima enemigos dormidos.$"

gAbilityDescription_StormDrain: @ 81FA0F6
	.string "Convierte agua en ATQ. ESP.$"

gAbilityDescription_MotorDrive: @ 81FA0F6
	.string "Cambia electricidad en VEL.$"

gAbilityDescription_SapSipper: @ 81FA0F6
	.string "Come PLANTA, sube ATQ.$"
	
gAbilityDescription_IronFists: @ 81FA0F6
	.string "Sube puñetazos.$"
	
gAbilityDescription_Sniper: @ 81FA0F6
	.string "Sube golpes críticos.$"

gAbilityDescription_Simple: @ 81FA0F6
	.string "Sube cambios de poder.$"

gAbilityDescription_Filter: @ 81FA0F6
	.string "Atenúa MOV. Muy efectivos.$"

gAbilityDescription_TintedLens: @ 81FA0F6
	.string "Sube MOV. Poco efectivos.$"

gAbilityDescription_FlowerGift: @ 81FA0F6
	.string "Sube ATQ. Y DEF. ES. En sol.$"

gAbilityDescription_Unaware: @ 81FA0F6
	.string "Ignora cambios de poder.$"
	
gAbilityDescription_Adaptability: @ 81FA0F6
	.string "Sube MOV. De su mismo tipo.$"
	
gAbilityDescription_Reckless: @ 81FA0F6
	.string "Sube MOV. Arriesgados.$"
	
gAbilityDescription_SkillLink: @ 81FA0F6
	.string "Mejora MOV. Multigolpe.$"
	
gAbilityDescription_Technician: @ 81FA0F6
	.string "Sube MOV. De baja potencia.$"
	
gAbilityDescription_IceBody: @ 81FA0F6
	.string "Recupera PS. En granizo.$"
	
gAbilityDescription_Hydratation: @ 81FA0F6
	.string "Cura estado en la lluvia.$"
	
gAbilityDescription_Heatproof: @ 81FA0F6
	.string "Atenúa MOV. De fuego.$"
	
gAbilityDescription_NoGuard: @ 81FA0F6
	.string "Los MOV. No fallan.$"
	
gAbilityDescription_Scrappy: @ 81FA0F6
	.string "Golpea fantasmas.$"
	
gAbilityDescription_RagePoint: @ 81FA0F6
	.string "Maximiza el ATAQUE.$"
	
gAbilityDescription_SnowCloak: @ 81FA0F6
	.string "Sube EVASIÓN en granizo.$"
	
gAbilityDescription_Normalize: @ 81FA0F6
	.string "Los MOV. Son tipo NORMAL.$"
	
gAbilityDescription_DrySkin: @ 81FA0F6
	.string "Prefiere la humedad.$"
	
gAbilityDescription_Aftermath: @ 81FA0F6
	.string "Hace daño al debilitarse.$"
	
gAbilityDescription_SnowWarning: @ 81FA0F6
	.string "Hace que granice en combate.$"
	
	.align 2
gAbilityDescriptions:: @ 81FA110
	.4byte gAbilityDescription_None
	.4byte gAbilityDescription_Stench
	.4byte gAbilityDescription_Drizzle
	.4byte gAbilityDescription_SpeedBoost
	.4byte gAbilityDescription_BattleArmor
	.4byte gAbilityDescription_Sturdy
	.4byte gAbilityDescription_Damp
	.4byte gAbilityDescription_Limber
	.4byte gAbilityDescription_SandVeil
	.4byte gAbilityDescription_Static
	.4byte gAbilityDescription_VoltAbsorb
	.4byte gAbilityDescription_WaterAbsorb
	.4byte gAbilityDescription_Oblivious
	.4byte gAbilityDescription_CloudNine
	.4byte gAbilityDescription_CompoundEyes
	.4byte gAbilityDescription_Insomnia
	.4byte gAbilityDescription_ColorChange
	.4byte gAbilityDescription_Immunity
	.4byte gAbilityDescription_FlashFire
	.4byte gAbilityDescription_ShieldDust
	.4byte gAbilityDescription_OwnTempo
	.4byte gAbilityDescription_SuctionCups
	.4byte gAbilityDescription_Intimidate
	.4byte gAbilityDescription_ShadowTag
	.4byte gAbilityDescription_RoughSkin
	.4byte gAbilityDescription_WonderGuard
	.4byte gAbilityDescription_Levitate
	.4byte gAbilityDescription_EffectSpore
	.4byte gAbilityDescription_Synchronize
	.4byte gAbilityDescription_ClearBody
	.4byte gAbilityDescription_NaturalCure
	.4byte gAbilityDescription_LightningRod
	.4byte gAbilityDescription_SereneGrace
	.4byte gAbilityDescription_SwiftSwim
	.4byte gAbilityDescription_Chlorophyll
	.4byte gAbilityDescription_Illuminate
	.4byte gAbilityDescription_Trace
	.4byte gAbilityDescription_HugePower
	.4byte gAbilityDescription_PoisonPoint
	.4byte gAbilityDescription_InnerFocus
	.4byte gAbilityDescription_MagmaArmor
	.4byte gAbilityDescription_WaterVeil
	.4byte gAbilityDescription_MagnetPull
	.4byte gAbilityDescription_Soundproof
	.4byte gAbilityDescription_RainDish
	.4byte gAbilityDescription_SandStream
	.4byte gAbilityDescription_Pressure
	.4byte gAbilityDescription_ThickFat
	.4byte gAbilityDescription_EarlyBird
	.4byte gAbilityDescription_FlameBody
	.4byte gAbilityDescription_RunAway
	.4byte gAbilityDescription_KeenEye
	.4byte gAbilityDescription_HyperCutter
	.4byte gAbilityDescription_Pickup
	.4byte gAbilityDescription_Truant
	.4byte gAbilityDescription_Hustle
	.4byte gAbilityDescription_CuteCharm
	.4byte gAbilityDescription_Plus
	.4byte gAbilityDescription_Minus
	.4byte gAbilityDescription_Forecast
	.4byte gAbilityDescription_StickyHold
	.4byte gAbilityDescription_ShedSkin
	.4byte gAbilityDescription_Guts
	.4byte gAbilityDescription_MarvelScale
	.4byte gAbilityDescription_LiquidOoze
	.4byte gAbilityDescription_Overgrow
	.4byte gAbilityDescription_Blaze
	.4byte gAbilityDescription_Torrent
	.4byte gAbilityDescription_Swarm
	.4byte gAbilityDescription_RockHead
	.4byte gAbilityDescription_Drought
	.4byte gAbilityDescription_ArenaTrap
	.4byte gAbilityDescription_VitalSpirit
	.4byte gAbilityDescription_WhiteSmoke
	.4byte gAbilityDescription_PurePower
	.4byte gAbilityDescription_ShellArmor
	.4byte gAbilityDescription_Cacophony
	.4byte gAbilityDescription_AirLock
	.4byte gAbilityDescription_BadDreams
	.4byte gAbilityDescription_StormDrain
	.4byte gAbilityDescription_MotorDrive
	.4byte gAbilityDescription_SapSipper
	.4byte gAbilityDescription_IronFists
	.4byte gAbilityDescription_Sniper
	.4byte gAbilityDescription_Simple
	.4byte gAbilityDescription_Filter
	.4byte gAbilityDescription_Filter
	.4byte gAbilityDescription_TintedLens
	.4byte gAbilityDescription_FlowerGift
	.4byte gAbilityDescription_Unaware
	.4byte gAbilityDescription_Adaptability
	.4byte gAbilityDescription_Reckless
	.4byte gAbilityDescription_SkillLink
	.4byte gAbilityDescription_Technician
	.4byte gAbilityDescription_IceBody
	.4byte gAbilityDescription_Hydratation
	.4byte gAbilityDescription_Heatproof
	.4byte gAbilityDescription_NoGuard
	.4byte gAbilityDescription_Scrappy
	.4byte gAbilityDescription_RagePoint
	.4byte gAbilityDescription_SnowCloak
	.4byte gAbilityDescription_Normalize
	.4byte gAbilityDescription_DrySkin
	.4byte gAbilityDescription_Aftermath
	.4byte gAbilityDescription_SnowWarning
